#!/usr/bin/env python3
"""
generate.py -- render the warehouse from model.yaml.

    python generate.py [--model model.yaml] [--out out]

Emits idempotent T-SQL (SQL Server 2016+). Every object is guarded by an
existence check; the files can be re-run at any time. Nothing in this file
knows the name of any entity: add entities by editing model.yaml only.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from edw.model import (Column, Dimension, DimensionKey, Fact, Model, SCHEMAS,
                       base_type, load_model, role_column, type_length)

# ---------------------------------------------------------------------------
# Small T-SQL rendering helpers
# ---------------------------------------------------------------------------

def q(s: str) -> str:
    """Single-quote a T-SQL string literal."""
    return "'" + s.replace("'", "''") + "'"


def to_text(expr: str, sql_type: str) -> str:
    """Deterministic text form of a value, used for hashes and source keys."""
    bt = base_type(sql_type)
    if bt == "date":
        return f"CONVERT(varchar(10), {expr}, 23)"
    if bt in ("datetime", "datetime2", "smalldatetime"):
        return f"CONVERT(varchar(27), {expr}, 121)"
    if bt == "time":
        return f"CONVERT(varchar(16), {expr}, 114)"
    return f"CONVERT(nvarchar(200), {expr})"


def key_expr(cols: list[tuple[str, str]], alias: str) -> str:
    """CONCAT of the typed text of each source column, '|' separated."""
    parts = [to_text(f"{alias}.{n}", t) for n, t in cols]
    if len(parts) == 1:
        return parts[0]
    joined = ", '|', ".join(parts)
    return f"CONCAT({joined})"


def hash_expr(model: Model, cols: list[Column], alias: str) -> str:
    alg = q(model.settings["hash_algorithm"])
    if not cols:
        return f"HASHBYTES({alg}, '')"
    parts = [f"ISNULL({to_text(f'{alias}.{c.name}', c.type)}, '')" for c in cols]
    if len(parts) == 1:
        return f"HASHBYTES({alg}, {parts[0]})"
    sep = ", '|', "
    return f"HASHBYTES({alg}, CONCAT({sep.join(parts)}))"


def null_spec(c: Column) -> str:
    return "NULL" if c.nullable else "NOT NULL"


def unknown_value(c: Column) -> str:
    """Literal for the Unknown member row (surrogate key -1)."""
    bt = base_type(c.type)
    if c.name.endswith("Flag"):
        return "'N'"
    if bt in ("varchar", "nvarchar", "char", "nchar"):
        n = type_length(c.type) or 1
        return q("Unknown"[:n])
    return "NULL"


def stub_proc(name: str) -> str:
    return (f"IF OBJECT_ID('{name}', 'P') IS NULL\n"
            f"    EXEC('CREATE PROCEDURE {name} AS BEGIN SET NOCOUNT ON; END');\nGO\n")


def stub_view(name: str) -> str:
    return (f"IF OBJECT_ID('{name}', 'V') IS NULL\n"
            f"    EXEC('CREATE VIEW {name} AS SELECT Placeholder = 1');\nGO\n")


def header(title: str) -> str:
    bar = "-" * 77
    return f"-- {bar}\n-- {title}\n-- GENERATED by generate.py from model.yaml. Do not edit by hand.\n-- {bar}\n"


def column_ddl(cols: list[Column], identity: str | None = None) -> str:
    width = max(len(c.name) for c in cols) + 1
    lines = []
    for c in cols:
        if c.name == identity:
            lines.append(f"    {c.name:<{width}} int IDENTITY(1,1) NOT NULL")
        else:
            lines.append(f"    {c.name:<{width}} {c.type} {null_spec(c)}")
    return ",\n".join(lines)


# ---------------------------------------------------------------------------
# 01 schemas
# ---------------------------------------------------------------------------

def gen_schemas(model: Model) -> str:
    out = [header("01 SCHEMAS")]
    for s in SCHEMAS:
        out.append(f"IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = '{s}')\n"
                   f"    EXEC('CREATE SCHEMA [{s}] AUTHORIZATION dbo');\nGO\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 02 control framework (pattern-fixed, model-independent)
# ---------------------------------------------------------------------------

def gen_control_framework(model: Model) -> str:
    return header("02 CONTROL FRAMEWORK: catalog + control + helper (tenant) schemas") + r"""
-- ===================== catalog: one row per pipeline object ==================
IF OBJECT_ID('catalog.Dimensions', 'U') IS NULL
CREATE TABLE catalog.Dimensions (
    DimensionKey             int IDENTITY(1,1) NOT NULL,
    DimensionName            varchar(128)  NOT NULL,
    SchemaName               varchar(128)  NOT NULL,
    TableName                varchar(128)  NOT NULL,
    StagingSchemaName        varchar(128)  NOT NULL,
    StagingTableName         varchar(128)  NOT NULL,
    TransformProcedureName   varchar(128)  NOT NULL,
    LoadOrder                int           NOT NULL,
    EnabledFlag              char(1)       NOT NULL CONSTRAINT DF_catalog_Dimensions_EnabledFlag DEFAULT 'Y',
    LastUpdatedDateTime      datetime      NOT NULL CONSTRAINT DF_catalog_Dimensions_LastUpdatedDateTime DEFAULT SYSDATETIME(),
    CONSTRAINT PK_catalog_Dimensions PRIMARY KEY CLUSTERED (DimensionKey),
    CONSTRAINT UQ_catalog_Dimensions_DimensionName UNIQUE (DimensionName)
);
GO

IF OBJECT_ID('catalog.Facts', 'U') IS NULL
CREATE TABLE catalog.Facts (
    FactKey                      int IDENTITY(1,1) NOT NULL,
    FactName                     varchar(128)  NOT NULL,
    SchemaName                   varchar(128)  NOT NULL,
    TableName                    varchar(128)  NOT NULL,
    StagingSchemaName            varchar(128)  NOT NULL,
    StagingTableName             varchar(128)  NOT NULL,
    FullRefreshProcedureName     varchar(128)  NOT NULL,
    PartialRefreshProcedureName  varchar(128)  NULL,
    LargeFactFlag                char(1)       NOT NULL,
    LoadOrder                    int           NOT NULL,
    EnabledFlag                  char(1)       NOT NULL CONSTRAINT DF_catalog_Facts_EnabledFlag DEFAULT 'Y',
    LastUpdatedDateTime          datetime      NOT NULL CONSTRAINT DF_catalog_Facts_LastUpdatedDateTime DEFAULT SYSDATETIME(),
    CONSTRAINT PK_catalog_Facts PRIMARY KEY CLUSTERED (FactKey),
    CONSTRAINT UQ_catalog_Facts_FactName UNIQUE (FactName)
);
GO

IF OBJECT_ID('catalog.StagingTable', 'U') IS NULL
CREATE TABLE catalog.StagingTable (
    StagingTableKey          int IDENTITY(1,1) NOT NULL,
    SchemaName               varchar(128)  NOT NULL,
    TableName                varchar(128)  NOT NULL,
    SourceSystemName         varchar(50)   NOT NULL,
    SourceObjectName         varchar(256)  NOT NULL,
    TargetEntityTypeName     varchar(20)   NOT NULL,   -- Dimension | Fact
    TargetEntityName         varchar(128)  NOT NULL,
    EnabledFlag              char(1)       NOT NULL CONSTRAINT DF_catalog_StagingTable_EnabledFlag DEFAULT 'Y',
    LastUpdatedDateTime      datetime      NOT NULL CONSTRAINT DF_catalog_StagingTable_LastUpdatedDateTime DEFAULT SYSDATETIME(),
    CONSTRAINT PK_catalog_StagingTable PRIMARY KEY CLUSTERED (StagingTableKey),
    CONSTRAINT UQ_catalog_StagingTable_Name UNIQUE (SchemaName, TableName)
);
GO

-- ===================== control: run history + instrumentation ================
IF OBJECT_ID('control.ProcessLog', 'U') IS NULL
CREATE TABLE control.ProcessLog (
    ProcessLogKey            int IDENTITY(1,1) NOT NULL,
    ParentProcessLogKey      int            NULL,
    ProcessName              varchar(200)   NOT NULL,
    ObjectName               varchar(200)   NULL,
    StatusCode               varchar(20)    NOT NULL,   -- Running | Success | Failure
    StartDateTime            datetime2(3)   NOT NULL,
    EndDateTime              datetime2(3)   NULL,
    RowsInserted             int            NULL,
    RowsUpdated              int            NULL,
    RowsExpired              int            NULL,
    ErrorMessage             nvarchar(max)  NULL,
    LastUpdatedDateTime      datetime       NOT NULL,
    CONSTRAINT PK_control_ProcessLog PRIMARY KEY CLUSTERED (ProcessLogKey)
);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_control_ProcessLog_ProcessName' AND object_id = OBJECT_ID('control.ProcessLog'))
    CREATE NONCLUSTERED INDEX IX_control_ProcessLog_ProcessName ON control.ProcessLog (ProcessName, StartDateTime);
GO

-- ===================== helper: TENANT configuration ==========================
-- The only place per-institution variation lives. The model never varies;
-- codes do.
IF OBJECT_ID('helper.AgeBandDefinition', 'U') IS NULL
CREATE TABLE helper.AgeBandDefinition (
    AgeBandDefinitionKey     int IDENTITY(1,1) NOT NULL,
    AgeBandCode              varchar(10)   NOT NULL,
    AgeBandName              varchar(50)   NOT NULL,
    MinimumAge               int           NOT NULL,
    MaximumAge               int           NOT NULL,
    SortOrder                int           NOT NULL,
    LastUpdatedDateTime      datetime      NOT NULL CONSTRAINT DF_helper_AgeBandDefinition_LastUpdatedDateTime DEFAULT SYSDATETIME(),
    CONSTRAINT PK_helper_AgeBandDefinition PRIMARY KEY CLUSTERED (AgeBandDefinitionKey),
    CONSTRAINT UQ_helper_AgeBandDefinition_AgeBandCode UNIQUE (AgeBandCode)
);
GO

IF OBJECT_ID('helper.DeliveryType', 'U') IS NULL
CREATE TABLE helper.DeliveryType (
    DeliveryTypeKey          int IDENTITY(1,1) NOT NULL,
    DeliveryTypeCode         varchar(10)   NOT NULL,
    DeliveryTypeName         varchar(50)   NOT NULL,
    DistanceEducationFlag    char(1)       NOT NULL,
    SortOrder                int           NOT NULL,
    LastUpdatedDateTime      datetime      NOT NULL CONSTRAINT DF_helper_DeliveryType_LastUpdatedDateTime DEFAULT SYSDATETIME(),
    CONSTRAINT PK_helper_DeliveryType PRIMARY KEY CLUSTERED (DeliveryTypeKey),
    CONSTRAINT UQ_helper_DeliveryType_DeliveryTypeCode UNIQUE (DeliveryTypeCode)
);
GO

IF OBJECT_ID('helper.SchoolName', 'U') IS NULL
CREATE TABLE helper.SchoolName (
    SchoolNameKey            int IDENTITY(1,1) NOT NULL,
    SchoolCode               varchar(20)   NOT NULL,
    SchoolName               varchar(200)  NOT NULL,
    SchoolShortName          varchar(50)   NOT NULL,
    PrimarySchoolFlag        char(1)       NOT NULL,
    LastUpdatedDateTime      datetime      NOT NULL CONSTRAINT DF_helper_SchoolName_LastUpdatedDateTime DEFAULT SYSDATETIME(),
    CONSTRAINT PK_helper_SchoolName PRIMARY KEY CLUSTERED (SchoolNameKey),
    CONSTRAINT UQ_helper_SchoolName_SchoolCode UNIQUE (SchoolCode)
);
GO

IF OBJECT_ID('helper.CodeMapping', 'U') IS NULL
CREATE TABLE helper.CodeMapping (
    CodeMappingKey           int IDENTITY(1,1) NOT NULL,
    MappingName              varchar(100)  NOT NULL,   -- the group, e.g. DeliveryType
    SourceSystemName         varchar(50)   NOT NULL,
    SourceCode               varchar(50)   NOT NULL,   -- what the source system says
    StandardCode             varchar(50)   NOT NULL,   -- what the warehouse stores
    StandardName             varchar(100)  NOT NULL,
    LastUpdatedDateTime      datetime      NOT NULL CONSTRAINT DF_helper_CodeMapping_LastUpdatedDateTime DEFAULT SYSDATETIME(),
    CONSTRAINT PK_helper_CodeMapping PRIMARY KEY CLUSTERED (CodeMappingKey),
    CONSTRAINT UQ_helper_CodeMapping_Source UNIQUE (MappingName, SourceSystemName, SourceCode)
);
GO

-- ===================== control procedures ====================================
""" + stub_proc("control.ExecutionStart") + r"""
ALTER PROCEDURE control.ExecutionStart
    @ProcessName         varchar(200),
    @ObjectName          varchar(200) = NULL,
    @ParentProcessLogKey int          = NULL,
    @ProcessLogKey       int          OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT control.ProcessLog (ParentProcessLogKey, ProcessName, ObjectName, StatusCode, StartDateTime, LastUpdatedDateTime)
    VALUES (@ParentProcessLogKey, @ProcessName, @ObjectName, 'Running', SYSDATETIME(), SYSDATETIME());
    SET @ProcessLogKey = SCOPE_IDENTITY();
END
GO

""" + stub_proc("control.ExecutionCompletion") + r"""
ALTER PROCEDURE control.ExecutionCompletion
    @ProcessLogKey int,
    @RowsInserted  int = NULL,
    @RowsUpdated   int = NULL,
    @RowsExpired   int = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE control.ProcessLog
       SET StatusCode          = 'Success',
           EndDateTime         = SYSDATETIME(),
           RowsInserted        = @RowsInserted,
           RowsUpdated         = @RowsUpdated,
           RowsExpired         = @RowsExpired,
           LastUpdatedDateTime = SYSDATETIME()
     WHERE ProcessLogKey = @ProcessLogKey;
END
GO

""" + stub_proc("control.ExecutionFailure") + r"""
ALTER PROCEDURE control.ExecutionFailure
    @ProcessLogKey int,
    @ErrorMessage  nvarchar(max)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE control.ProcessLog
       SET StatusCode          = 'Failure',
           EndDateTime         = SYSDATETIME(),
           ErrorMessage        = @ErrorMessage,
           LastUpdatedDateTime = SYSDATETIME()
     WHERE ProcessLogKey = @ProcessLogKey;
END
GO

""" + stub_proc("control.ValidateTableName") + r"""
-- Guards every dynamic-SQL path: the name must be a plain identifier and the
-- table must exist. Throws otherwise.
ALTER PROCEDURE control.ValidateTableName
    @SchemaName sysname,
    @TableName  sysname
AS
BEGIN
    SET NOCOUNT ON;
    IF @SchemaName IS NULL OR @TableName IS NULL
        THROW 50001, 'Schema and table name are required.', 1;
    IF PATINDEX('%[^A-Za-z0-9_]%', @SchemaName) > 0 OR PATINDEX('%[^A-Za-z0-9_]%', @TableName) > 0
        THROW 50002, 'Schema and table names may contain only letters, digits and underscores.', 1;
    IF OBJECT_ID(QUOTENAME(@SchemaName) + '.' + QUOTENAME(@TableName), 'U') IS NULL
    BEGIN
        DECLARE @Message nvarchar(400) = CONCAT('Table ', @SchemaName, '.', @TableName, ' does not exist.');
        THROW 50003, @Message, 1;
    END
END
GO

""" + stub_proc("control.PrepareStagingTable") + r"""
-- Called by the EXTRACT layer before loading a staging table. Generic:
-- validates the name, confirms the table is registered and enabled in
-- catalog.StagingTable, then truncates it.
ALTER PROCEDURE control.PrepareStagingTable
    @SchemaName          sysname,
    @TableName           sysname,
    @ParentProcessLogKey int = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @ProcessLogKey int, @ObjectName varchar(200) = CONCAT(@SchemaName, '.', @TableName);
    EXEC control.ExecutionStart @ProcessName = 'PrepareStagingTable', @ObjectName = @ObjectName,
                                @ParentProcessLogKey = @ParentProcessLogKey, @ProcessLogKey = @ProcessLogKey OUTPUT;
    BEGIN TRY
        EXEC control.ValidateTableName @SchemaName, @TableName;
        IF NOT EXISTS (SELECT 1 FROM catalog.StagingTable
                        WHERE SchemaName = @SchemaName AND TableName = @TableName AND EnabledFlag = 'Y')
        BEGIN
            DECLARE @Message nvarchar(400) = CONCAT('Staging table ', @ObjectName, ' is not registered and enabled in catalog.StagingTable.');
            THROW 50004, @Message, 1;
        END
        DECLARE @Sql nvarchar(max) = CONCAT('TRUNCATE TABLE ', QUOTENAME(@SchemaName), '.', QUOTENAME(@TableName), ';');
        EXEC sp_executesql @Sql;
        EXEC control.ExecutionCompletion @ProcessLogKey;
    END TRY
    BEGIN CATCH
        DECLARE @ErrorMessage nvarchar(max) = ERROR_MESSAGE();
        EXEC control.ExecutionFailure @ProcessLogKey, @ErrorMessage;
        THROW;
    END CATCH
END
GO
"""


# ---------------------------------------------------------------------------
# 03 staging
# ---------------------------------------------------------------------------

def gen_staging(model: Model) -> str:
    out = [header("03 STAGING: 1:1 landing tables, no transformation")]
    for entity in [*model.dims, *model.facts]:
        cols = entity.staging_columns
        out.append(f"-- {entity.staging}  <-  {entity.source_system}.{entity.source_object}\n"
                   f"IF OBJECT_ID('{entity.staging}', 'U') IS NULL\n"
                   f"CREATE TABLE {entity.staging} (\n{column_ddl(cols)}\n);\nGO\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 04 dimensions
# ---------------------------------------------------------------------------

def gen_dimensions(model: Model) -> str:
    out = [header("04 DIMENSIONS: tables, indexes, Unknown member rows")]
    unk = model.settings["unknown_member_key"]
    alg = q(model.settings["hash_algorithm"])
    for d in model.dims:
        cols = d.all_columns
        out.append(f"-- {d.table}: {d.description}\n"
                   f"IF OBJECT_ID('{d.table}', 'U') IS NULL\n"
                   f"CREATE TABLE {d.table} (\n{column_ddl(cols, identity=d.key)},\n"
                   f"    CONSTRAINT PK_dim_{d.name} PRIMARY KEY CLUSTERED ({d.key})\n);\nGO\n")
        ix = f"IX_dim_{d.name}_SourceSystemKey"
        out.append(f"IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = '{ix}' AND object_id = OBJECT_ID('{d.table}'))\n"
                   f"    CREATE NONCLUSTERED INDEX {ix} ON {d.table}\n"
                   f"        ({d.conf('SourceSystemKey')}, {d.conf('SourceSystemName')}, {d.conf('ActiveRecordFlag')});\nGO\n")
        # Unknown member so every fact FK always resolves.
        names = ", ".join(c.name for c in cols)
        values = [str(unk)] + [unknown_value(a) for a in d.attributes] + [
            "'Unknown'", "'Unknown'", f"HASHBYTES({alg}, 'Unknown')", f"HASHBYTES({alg}, 'Unknown')",
            "'Y'", "'1900-01-01'", q(model.settings["end_of_time"]), "SYSDATETIME()"]
        out.append(f"IF NOT EXISTS (SELECT 1 FROM {d.table} WHERE {d.key} = {unk})\nBEGIN\n"
                   f"    SET IDENTITY_INSERT {d.table} ON;\n"
                   f"    INSERT {d.table} ({names})\n    VALUES ({', '.join(values)});\n"
                   f"    SET IDENTITY_INSERT {d.table} OFF;\nEND\nGO\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 05 facts
# ---------------------------------------------------------------------------

def gen_facts(model: Model) -> str:
    out = [header("05 FACTS: tables and indexes")]
    for f in model.facts:
        cols = f.all_columns
        out.append(f"-- {f.table}: {f.description}  (grain: {f.grain})\n"
                   f"IF OBJECT_ID('{f.table}', 'U') IS NULL\n"
                   f"CREATE TABLE {f.table} (\n{column_ddl(cols, identity=f.key)},\n"
                   f"    CONSTRAINT PK_fact_{f.name} PRIMARY KEY CLUSTERED ({f.key})\n);\nGO\n")
        keys = [f"{r}Key" for r in f.index_keys]
        ix = f"IX_fact_{f.name}_" + "_".join(keys)
        out.append(f"IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = '{ix}' AND object_id = OBJECT_ID('{f.table}'))\n"
                   f"    CREATE NONCLUSTERED INDEX {ix} ON {f.table} ({', '.join(keys)});\nGO\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 06 foreign keys
# ---------------------------------------------------------------------------

def fk_name(f: Fact, dk: DimensionKey) -> str:
    return f"FK_fact_{f.name}_{dk.column}"


def gen_foreign_keys(model: Model) -> str:
    out = [header("06 FOREIGN KEYS: fact -> dimension")]
    for f in model.facts:
        for dk in f.dimension_keys:
            name = fk_name(f, dk)
            out.append(f"IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = '{name}')\n"
                       f"    ALTER TABLE {f.table} WITH CHECK ADD CONSTRAINT {name}\n"
                       f"        FOREIGN KEY ({dk.column}) REFERENCES {dk.dimension.table} ({dk.dimension.key});\nGO\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 07 lookup views: one per dimension role
# ---------------------------------------------------------------------------

def gen_lookup_views(model: Model) -> str:
    out = [header("07 LOOKUP VIEWS: one view per dimension role (never duplicate a dim table)")]
    for role, d in model.roles:
        view = f"lookup.{role}"
        width = max(len(role_column(role, d.name, c.name)) for c in d.all_columns) + 1
        sel = ",\n".join(f"    {role_column(role, d.name, c.name):<{width}}= d.{c.name}" for c in d.all_columns)
        note = "" if role == d.name else f"  -- {d.name} played as {role}"
        out.append(stub_view(view) + f"ALTER VIEW {view}{note}\nAS\nSELECT\n{sel}\nFROM {d.table} AS d;\nGO\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 08 data views: one consumption view per fact
# ---------------------------------------------------------------------------

def data_column(dk: DimensionKey, c: Column) -> str:
    """Role-qualified name so a wide join can never collide."""
    name = role_column(dk.role, dk.dimension.name, c.name)
    return name if name.startswith(dk.role) else f"{dk.role}{name}"


def data_view_columns(f: Fact) -> list[tuple[str, str]]:
    """(output name, source expression) for the data view -- used by validate.py too."""
    cols = [(f.key, f"f.{f.key}")]
    for dk in f.dimension_keys:
        for c in dk.dimension.attributes:
            cols.append((data_column(dk, c), f"{dk.role}.{role_column(dk.role, dk.dimension.name, c.name)}"))
    for m in f.measures:
        cols.append((m.name, f"f.{m.name}"))
    for c in f.conformance_columns:
        cols.append((c.name, f"f.{c.name}"))
    return cols


def gen_data_views(model: Model) -> str:
    out = [header("08 DATA VIEWS: one consumption view per fact, keys resolved to names")]
    for f in model.facts:
        view = f"data.{f.name}"
        cols = data_view_columns(f)
        width = max(len(n) for n, _ in cols) + 1
        sel = ",\n".join(f"    {n:<{width}}= {e}" for n, e in cols)
        joins = "\n".join(f"JOIN lookup.{dk.role} AS {dk.role} ON {dk.role}.{dk.column} = f.{dk.column}"
                          for dk in f.dimension_keys)
        out.append(stub_view(view) + f"ALTER VIEW {view}\nAS\nSELECT\n{sel}\nFROM {f.table} AS f\n{joins};\nGO\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 09 ETL procedures
# ---------------------------------------------------------------------------

def proc_prologue(proc: str, obj: str, extra_params: str = "") -> str:
    return f"""ALTER PROCEDURE {proc}
    @ParentProcessLogKey int  = NULL,
    @LoadDate            date = NULL{extra_params}
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    DECLARE @ProcessLogKey int, @RowsInserted int = 0, @RowsUpdated int = 0, @RowsExpired int = 0;
    DECLARE @SourceSystemName varchar(50);
    SET @LoadDate = ISNULL(@LoadDate, CAST(SYSDATETIME() AS date));
    EXEC control.ExecutionStart @ProcessName = '{proc.split('.')[1]}', @ObjectName = '{obj}',
                                @ParentProcessLogKey = @ParentProcessLogKey, @ProcessLogKey = @ProcessLogKey OUTPUT;
    BEGIN TRY
"""


PROC_EPILOGUE = """        EXEC control.ExecutionCompletion @ProcessLogKey, @RowsInserted, @RowsUpdated, @RowsExpired;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        DECLARE @ErrorMessage nvarchar(max) = ERROR_MESSAGE();
        EXEC control.ExecutionFailure @ProcessLogKey, @ErrorMessage;
        THROW;
    END CATCH
END
GO
"""


def source_system_lookup(staging_table: str) -> str:
    return (f"        SELECT @SourceSystemName = SourceSystemName FROM catalog.StagingTable\n"
            f"         WHERE SchemaName = 'stg' AND TableName = '{staging_table}';\n"
            f"        SET @SourceSystemName = ISNULL(@SourceSystemName, 'Unknown');\n")


def dim_value_exprs(d: Dimension) -> tuple[dict[str, str], list[str]]:
    """
    Per-attribute T-SQL value expression over the staging row alias `src`
    (and helper.CodeMapping aliases), plus the join clauses those need.
    """
    exprs: dict[str, str] = {}
    joins: list[str] = []
    for a in d.attributes:
        if a.mapping:
            alias = f"map_{a.name}"
            joins.append(f"            LEFT JOIN helper.CodeMapping AS {alias}\n"
                         f"                   ON {alias}.MappingName = {q(a.mapping)}\n"
                         f"                  AND {alias}.SourceSystemName = @SourceSystemName\n"
                         f"                  AND {alias}.SourceCode = CONVERT(varchar(50), src.{a.name})")
            exprs[a.name] = f"COALESCE(map_{a.name}.StandardCode, src.{a.name})"
        elif a.mapping_name_of:
            exprs[a.name] = f"COALESCE(map_{a.mapping_name_of}.StandardName, src.{a.mapping_name_of})"
        elif a.expression:
            exprs[a.name] = a.expression  # placeholders resolved below
        else:
            exprs[a.name] = f"src.{a.name}"
    # resolve {Placeholder} references in expressions against the other expressions
    for a in d.attributes:
        if a.expression:
            e = a.expression
            for other, oe in exprs.items():
                if other != a.name:
                    e = e.replace("{" + other + "}", f"({oe})")
            exprs[a.name] = e
    return exprs, joins


def gen_dim_proc(model: Model, d: Dimension) -> str:
    proc = f"etl.Dim_{d.name}_InsertUpdate"
    exprs, joins = dim_value_exprs(d)
    key_cols = [(c.name, c.type) for c in d.source_key_columns]
    key = key_expr(key_cols, "src")
    not_null = " AND ".join(f"src.{n} IS NOT NULL" for n, _ in key_cols)
    scd1, scd2 = d.scd_attributes(1), d.scd_attributes(2)
    width = max(len(a.name) for a in d.attributes) + 1

    inner_cols = ",\n".join(f"                {a.name:<{width}}= CAST({exprs[a.name]} AS {a.type})" for a in d.attributes)
    attr_names = ", ".join(a.name for a in d.attributes)
    hash1, hash2 = hash_expr(model, scd1, "s"), hash_expr(model, scd2, "s")
    conf = [d.conf(s) for s in ("SourceSystemName", "SourceSystemKey", "SCDType1HashValue", "SCDType2HashValue",
                                "ActiveRecordFlag", "StartEffectiveDate", "EndEffectiveDate", "LastUpdatedDateTime")]
    ssn, ssk, h1, h2, active, start, end, upd = conf
    eot = q(model.settings["end_of_time"])
    join_src = "\n".join(joins)

    body = f"""{source_system_lookup(d.staging_table)}
        -- 1. Shape the source: one row per source key, mapped/derived values, both hashes.
        IF OBJECT_ID('tempdb..#Source') IS NOT NULL DROP TABLE #Source;
        SELECT
            s.SourceSystemKey,
            {attr_names},
            SCDType1HashValue = {hash1},
            SCDType2HashValue = {hash2}
        INTO #Source
        FROM (
            SELECT
                SourceSystemKey = CAST({key} AS varchar(200)),
{inner_cols},
                RowNumber = ROW_NUMBER() OVER (PARTITION BY {key} ORDER BY (SELECT NULL))
            FROM {d.staging} AS src
{join_src}
            WHERE {not_null}
        ) AS s
        WHERE s.RowNumber = 1;
        CREATE UNIQUE CLUSTERED INDEX IX_Source ON #Source (SourceSystemKey);

        BEGIN TRANSACTION;
"""
    if scd2:
        body += f"""
        -- 2. SCD Type 2: close the active row when a Type 2 attribute changed.
        UPDATE d
           SET d.{end} = @LoadDate,
               d.{active} = 'N',
               d.{upd} = SYSDATETIME()
          FROM {d.table} AS d
          JOIN #Source AS s ON s.SourceSystemKey = d.{ssk}
         WHERE d.{ssn} = @SourceSystemName
           AND d.{active} = 'Y'
           AND d.{h2} <> s.SCDType2HashValue;
        SET @RowsExpired = @@ROWCOUNT;
"""
    body += f"""
        -- 3. Insert every source row that has no active dimension row (new keys and re-opened Type 2 keys).
        INSERT {d.table} ({attr_names}, {', '.join(conf)})
        SELECT {', '.join('s.' + a.name for a in d.attributes)},
               @SourceSystemName, s.SourceSystemKey, s.SCDType1HashValue, s.SCDType2HashValue,
               'Y', @LoadDate, {eot}, SYSDATETIME()
          FROM #Source AS s
         WHERE NOT EXISTS (SELECT 1 FROM {d.table} AS d
                            WHERE d.{ssk} = s.SourceSystemKey
                              AND d.{ssn} = @SourceSystemName
                              AND d.{active} = 'Y');
        SET @RowsInserted = @@ROWCOUNT;
"""
    if scd1:
        sets = ",\n".join(f"               d.{a.name} = s.{a.name}" for a in scd1)
        body += f"""
        -- 4. SCD Type 1: overwrite in place on every version of the key.
        UPDATE d
           SET
{sets},
               d.{h1} = s.SCDType1HashValue,
               d.{upd} = SYSDATETIME()
          FROM {d.table} AS d
          JOIN #Source AS s ON s.SourceSystemKey = d.{ssk}
         WHERE d.{ssn} = @SourceSystemName
           AND d.{h1} <> s.SCDType1HashValue;
        SET @RowsUpdated = @@ROWCOUNT;
"""
    body += "\n        COMMIT TRANSACTION;\n"
    return stub_proc(proc) + proc_prologue(proc, d.table) + body + PROC_EPILOGUE


def fact_select(model: Model, f: Fact) -> str:
    """The INSERT ... SELECT shared by full and partial refresh."""
    unk = model.settings["unknown_member_key"]
    width = max(len(c.name) for c in f.all_columns) + 1
    sel = []
    for dk in f.dimension_keys:
        sel.append(f"               {dk.column:<{width}}= ISNULL({dk.role}.{dk.dimension.key}, {unk})")
    for m in f.measures:
        sel.append(f"               {m.name:<{width}}= src.{m.name}")
    key_cols = [(n, f.staging_column(n).type) for n in f.source_key]
    sel.append(f"               {f.conf('SourceSystemName'):<{width}}= @SourceSystemName")
    sel.append(f"               {f.conf('SourceSystemKey'):<{width}}= CAST({key_expr(key_cols, 'src')} AS varchar(200))")
    sel.append(f"               {f.conf('LastUpdatedDateTime'):<{width}}= SYSDATETIME()")
    joins = []
    for dk in f.dimension_keys:
        d = dk.dimension
        cols = [(s, c.type) for s, c in zip(dk.source, d.source_key_columns)]
        joins.append(f"          LEFT JOIN {d.table} AS {dk.role}\n"
                     f"                 ON {dk.role}.{d.conf('SourceSystemKey')} = {key_expr(cols, 'src')}\n"
                     f"                AND {dk.role}.{d.conf('ActiveRecordFlag')} = 'Y'")
    names = [c.name for c in f.all_columns if c.name != f.key]
    return (f"        INSERT {f.table} ({', '.join(names)})\n"
            f"        SELECT\n" + ",\n".join(sel) + f"\n          FROM {f.staging} AS src\n" + "\n".join(joins) + ";\n")


def gen_fact_full_proc(model: Model, f: Fact) -> str:
    proc = f"etl.Fact_{f.name}_FullRefresh"
    body = (source_system_lookup(f.staging_table)
            + "\n        BEGIN TRANSACTION;\n"
            + f"        TRUNCATE TABLE {f.table};\n\n"
            + fact_select(model, f)
            + "        SET @RowsInserted = @@ROWCOUNT;\n        COMMIT TRANSACTION;\n")
    return stub_proc(proc) + proc_prologue(proc, f.table) + body + PROC_EPILOGUE


def gen_fact_partial_proc(model: Model, f: Fact) -> str:
    proc = f"etl.Fact_{f.name}_PartialRefresh"
    dk = f.dimension_key(f.partial_refresh_role)
    d = dk.dimension
    unk = model.settings["unknown_member_key"]
    cols = [(s, c.type) for s, c in zip(dk.source, d.source_key_columns)]
    body = (source_system_lookup(f.staging_table)
            + f"""
        -- Scope: every {dk.role} present in staging is replaced in full.
        IF OBJECT_ID('tempdb..#Scope') IS NOT NULL DROP TABLE #Scope;
        SELECT DISTINCT {dk.column} = ISNULL({dk.role}.{d.key}, {unk})
          INTO #Scope
          FROM {f.staging} AS src
          LEFT JOIN {d.table} AS {dk.role}
                 ON {dk.role}.{d.conf('SourceSystemKey')} = {key_expr(cols, 'src')}
                AND {dk.role}.{d.conf('ActiveRecordFlag')} = 'Y';

        BEGIN TRANSACTION;
        DELETE f FROM {f.table} AS f WHERE f.{dk.column} IN (SELECT {dk.column} FROM #Scope);
        SET @RowsExpired = @@ROWCOUNT;

""" + fact_select(model, f)
            + "        SET @RowsInserted = @@ROWCOUNT;\n        COMMIT TRANSACTION;\n")
    return stub_proc(proc) + proc_prologue(proc, f.table) + body + PROC_EPILOGUE


def gen_etl_procedures(model: Model) -> str:
    out = [header("09 ETL PROCEDURES: staging -> dim/fact. All transform logic lives here.")]
    for d in model.dims:
        out.append(gen_dim_proc(model, d))
    for f in model.facts:
        out.append(gen_fact_full_proc(model, f))
        if f.large:
            out.append(gen_fact_partial_proc(model, f))
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 10 orchestrators (metadata-driven: walk catalog rows in LoadOrder)
# ---------------------------------------------------------------------------

def gen_orchestrators(model: Model) -> str:
    return header("10 ORCHESTRATORS: thin, catalog-driven, dimensions before facts") + stub_proc("etl.Load_Dimensions") + r"""
ALTER PROCEDURE etl.Load_Dimensions
    @ParentProcessLogKey int  = NULL,
    @LoadDate            date = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @ProcessLogKey int, @ProcedureName sysname, @Sql nvarchar(max), @Count int = 0;
    EXEC control.ExecutionStart @ProcessName = 'Load_Dimensions', @ObjectName = 'catalog.Dimensions',
                                @ParentProcessLogKey = @ParentProcessLogKey, @ProcessLogKey = @ProcessLogKey OUTPUT;
    BEGIN TRY
        DECLARE DimensionCursor CURSOR LOCAL FAST_FORWARD FOR
            SELECT TransformProcedureName FROM catalog.Dimensions WHERE EnabledFlag = 'Y' ORDER BY LoadOrder, DimensionName;
        OPEN DimensionCursor;
        FETCH NEXT FROM DimensionCursor INTO @ProcedureName;
        WHILE @@FETCH_STATUS = 0
        BEGIN
            IF OBJECT_ID('etl.' + QUOTENAME(@ProcedureName), 'P') IS NULL
            BEGIN
                DECLARE @Missing nvarchar(400) = CONCAT('Catalogued procedure etl.', @ProcedureName, ' does not exist.');
                THROW 50010, @Missing, 1;
            END
            SET @Sql = CONCAT('EXEC etl.', QUOTENAME(@ProcedureName), ' @ParentProcessLogKey = @Parent, @LoadDate = @LoadDate;');
            EXEC sp_executesql @Sql, N'@Parent int, @LoadDate date', @Parent = @ProcessLogKey, @LoadDate = @LoadDate;
            SET @Count += 1;
            FETCH NEXT FROM DimensionCursor INTO @ProcedureName;
        END
        CLOSE DimensionCursor; DEALLOCATE DimensionCursor;
        EXEC control.ExecutionCompletion @ProcessLogKey, @RowsInserted = @Count;
    END TRY
    BEGIN CATCH
        IF CURSOR_STATUS('local', 'DimensionCursor') >= 0 BEGIN CLOSE DimensionCursor; DEALLOCATE DimensionCursor; END
        DECLARE @ErrorMessage nvarchar(max) = ERROR_MESSAGE();
        EXEC control.ExecutionFailure @ProcessLogKey, @ErrorMessage;
        THROW;
    END CATCH
END
GO

""" + stub_proc("etl.Load_Facts") + r"""
ALTER PROCEDURE etl.Load_Facts
    @ParentProcessLogKey int         = NULL,
    @LoadDate            date        = NULL,
    @RefreshMode         varchar(10) = 'Full'      -- Full | Partial (Partial falls back to Full for small facts)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @ProcessLogKey int, @ProcedureName sysname, @Sql nvarchar(max), @Count int = 0;
    EXEC control.ExecutionStart @ProcessName = 'Load_Facts', @ObjectName = 'catalog.Facts',
                                @ParentProcessLogKey = @ParentProcessLogKey, @ProcessLogKey = @ProcessLogKey OUTPUT;
    BEGIN TRY
        IF @RefreshMode NOT IN ('Full', 'Partial') THROW 50011, 'RefreshMode must be Full or Partial.', 1;
        DECLARE FactCursor CURSOR LOCAL FAST_FORWARD FOR
            SELECT CASE WHEN @RefreshMode = 'Partial' AND PartialRefreshProcedureName IS NOT NULL
                        THEN PartialRefreshProcedureName ELSE FullRefreshProcedureName END
              FROM catalog.Facts WHERE EnabledFlag = 'Y' ORDER BY LoadOrder, FactName;
        OPEN FactCursor;
        FETCH NEXT FROM FactCursor INTO @ProcedureName;
        WHILE @@FETCH_STATUS = 0
        BEGIN
            IF OBJECT_ID('etl.' + QUOTENAME(@ProcedureName), 'P') IS NULL
            BEGIN
                DECLARE @Missing nvarchar(400) = CONCAT('Catalogued procedure etl.', @ProcedureName, ' does not exist.');
                THROW 50010, @Missing, 1;
            END
            SET @Sql = CONCAT('EXEC etl.', QUOTENAME(@ProcedureName), ' @ParentProcessLogKey = @Parent, @LoadDate = @LoadDate;');
            EXEC sp_executesql @Sql, N'@Parent int, @LoadDate date', @Parent = @ProcessLogKey, @LoadDate = @LoadDate;
            SET @Count += 1;
            FETCH NEXT FROM FactCursor INTO @ProcedureName;
        END
        CLOSE FactCursor; DEALLOCATE FactCursor;
        EXEC control.ExecutionCompletion @ProcessLogKey, @RowsInserted = @Count;
    END TRY
    BEGIN CATCH
        IF CURSOR_STATUS('local', 'FactCursor') >= 0 BEGIN CLOSE FactCursor; DEALLOCATE FactCursor; END
        DECLARE @ErrorMessage nvarchar(max) = ERROR_MESSAGE();
        EXEC control.ExecutionFailure @ProcessLogKey, @ErrorMessage;
        THROW;
    END CATCH
END
GO

""" + stub_proc("etl.Load_Warehouse") + r"""
-- The single entry point. Dimensions first, always; then facts.
ALTER PROCEDURE etl.Load_Warehouse
    @LoadDate    date        = NULL,
    @RefreshMode varchar(10) = 'Full'
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @ProcessLogKey int;
    SET @LoadDate = ISNULL(@LoadDate, CAST(SYSDATETIME() AS date));
    EXEC control.ExecutionStart @ProcessName = 'Load_Warehouse', @ObjectName = NULL,
                                @ParentProcessLogKey = NULL, @ProcessLogKey = @ProcessLogKey OUTPUT;
    BEGIN TRY
        EXEC etl.Load_Dimensions @ParentProcessLogKey = @ProcessLogKey, @LoadDate = @LoadDate;
        EXEC etl.Load_Facts      @ParentProcessLogKey = @ProcessLogKey, @LoadDate = @LoadDate, @RefreshMode = @RefreshMode;
        EXEC control.ExecutionCompletion @ProcessLogKey;
    END TRY
    BEGIN CATCH
        DECLARE @ErrorMessage nvarchar(max) = ERROR_MESSAGE();
        EXEC control.ExecutionFailure @ProcessLogKey, @ErrorMessage;
        THROW;
    END CATCH
END
GO
"""


# ---------------------------------------------------------------------------
# 11 catalog seed
# ---------------------------------------------------------------------------

def upsert(table: str, where: str, values: dict[str, str]) -> str:
    """Idempotent catalog row: insert when absent, otherwise refresh every column."""
    cols = ", ".join(values)
    vals = ", ".join(values.values())
    sets = ",\n           ".join(f"{k} = {v}" for k, v in values.items())
    return (f"IF NOT EXISTS (SELECT 1 FROM {table} WHERE {where})\n"
            f"    INSERT {table} ({cols}) VALUES ({vals});\nELSE\n"
            f"    UPDATE {table}\n       SET {sets},\n           LastUpdatedDateTime = SYSDATETIME()\n"
            f"     WHERE {where};\nGO\n")


def gen_catalog_seed(model: Model) -> str:
    out = [header("11 CATALOG SEED: every entity registered as metadata (the pipeline runs off these rows)")]
    for i, d in enumerate(model.dims, start=1):
        out.append(upsert("catalog.Dimensions", f"DimensionName = {q(d.name)}", {
            "DimensionName": q(d.name), "SchemaName": "'dim'", "TableName": q(d.name),
            "StagingSchemaName": "'stg'", "StagingTableName": q(d.staging_table),
            "TransformProcedureName": q(f"Dim_{d.name}_InsertUpdate"), "LoadOrder": str(i), "EnabledFlag": "'Y'"}))
    for i, f in enumerate(model.facts, start=1):
        out.append(upsert("catalog.Facts", f"FactName = {q(f.name)}", {
            "FactName": q(f.name), "SchemaName": "'fact'", "TableName": q(f.name),
            "StagingSchemaName": "'stg'", "StagingTableName": q(f.staging_table),
            "FullRefreshProcedureName": q(f"Fact_{f.name}_FullRefresh"),
            "PartialRefreshProcedureName": q(f"Fact_{f.name}_PartialRefresh") if f.large else "NULL",
            "LargeFactFlag": "'Y'" if f.large else "'N'", "LoadOrder": str(i), "EnabledFlag": "'Y'"}))
    for kind, entities in (("Dimension", model.dims), ("Fact", model.facts)):
        for e in entities:
            out.append(upsert("catalog.StagingTable", f"SchemaName = 'stg' AND TableName = {q(e.staging_table)}", {
                "SchemaName": "'stg'", "TableName": q(e.staging_table), "SourceSystemName": q(e.source_system),
                "SourceObjectName": q(e.source_object), "TargetEntityTypeName": q(kind),
                "TargetEntityName": q(e.name), "EnabledFlag": "'Y'"}))
    return "\n".join(out)


# ---------------------------------------------------------------------------
# 99 drop all
# ---------------------------------------------------------------------------

def gen_drop_all(model: Model) -> str:
    out = [header("99 DROP ALL: reverse dependency order, every step guarded")]

    def drop(kind: str, name: str, code: str) -> str:
        return f"IF OBJECT_ID('{name}', '{code}') IS NOT NULL DROP {kind} {name};\n"

    out.append("-- foreign keys")
    for f in model.facts:
        for dk in f.dimension_keys:
            n = fk_name(f, dk)
            out.append(f"IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = '{n}') ALTER TABLE {f.table} DROP CONSTRAINT {n};")
    out.append("GO\n-- views")
    for f in model.facts:
        out.append(drop("VIEW", f"data.{f.name}", "V"))
    for role, _ in model.roles:
        out.append(drop("VIEW", f"lookup.{role}", "V"))
    out.append("GO\n-- procedures")
    for p in ("etl.Load_Warehouse", "etl.Load_Facts", "etl.Load_Dimensions"):
        out.append(drop("PROCEDURE", p, "P"))
    for f in model.facts:
        out.append(drop("PROCEDURE", f"etl.Fact_{f.name}_FullRefresh", "P"))
        out.append(drop("PROCEDURE", f"etl.Fact_{f.name}_PartialRefresh", "P"))
    for d in model.dims:
        out.append(drop("PROCEDURE", f"etl.Dim_{d.name}_InsertUpdate", "P"))
    for p in ("control.PrepareStagingTable", "control.ValidateTableName", "control.ExecutionFailure",
              "control.ExecutionCompletion", "control.ExecutionStart"):
        out.append(drop("PROCEDURE", p, "P"))
    out.append("GO\n-- tables")
    for f in model.facts:
        out.append(drop("TABLE", f.table, "U"))
    for d in model.dims:
        out.append(drop("TABLE", d.table, "U"))
    for e in [*model.dims, *model.facts]:
        out.append(drop("TABLE", e.staging, "U"))
    for t in ("helper.CodeMapping", "helper.SchoolName", "helper.DeliveryType", "helper.AgeBandDefinition",
              "control.ProcessLog", "catalog.StagingTable", "catalog.Facts", "catalog.Dimensions"):
        out.append(drop("TABLE", t, "U"))
    out.append("GO\n-- schemas")
    for s in reversed(SCHEMAS):
        out.append(f"IF EXISTS (SELECT 1 FROM sys.schemas WHERE name = '{s}') EXEC('DROP SCHEMA [{s}]');")
    out.append("GO\n")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

OUTPUTS = [
    ("01_schemas.sql",           gen_schemas),
    ("02_control_framework.sql", gen_control_framework),
    ("03_staging.sql",           gen_staging),
    ("04_dimensions.sql",        gen_dimensions),
    ("05_facts.sql",             gen_facts),
    ("06_foreign_keys.sql",      gen_foreign_keys),
    ("07_lookup_views.sql",      gen_lookup_views),
    ("08_data_views.sql",        gen_data_views),
    ("09_etl_procedures.sql",    gen_etl_procedures),
    ("10_orchestrators.sql",     gen_orchestrators),
    ("11_catalog_seed.sql",      gen_catalog_seed),
    ("99_drop_all.sql",          gen_drop_all),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model", default="model.yaml")
    ap.add_argument("--out", default="out")
    args = ap.parse_args()

    model = load_model(args.model)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    for filename, fn in OUTPUTS:
        text = fn(model)
        (out_dir / filename).write_text(text)
        print(f"wrote {out_dir / filename}  ({text.count(chr(10))} lines)")
    print(f"model: {len(model.dims)} dims, {len(model.facts)} facts, {len(model.roles)} roles")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
