-- ---------------------------------------------------------------------------
-- data.StudentRisk: one row per enrolled student per term, combining SIS,
-- LMS, CRM, financial aid, and ITSM signals into a composite risk score.
--
-- GENERATED by dashboard/derive_weights.py on 2026-08-30 -- do not edit weights
-- by hand; re-run the script after reseeding. Weights are log-odds-ratio
-- based, derived from which signals actually preceded non-return in this
-- warehouse's data:
--   Term GPA below 2.0                             weight  0  (odds ratio 1.04)
--   Completion ratio below 50%                     weight  0  (odds ratio 1.04)
--   Completion ratio dropped >30 points            weight  1  (odds ratio 1.28)
--   No LMS activity for 14+ days                   weight 17  (odds ratio 68.68)
--   LMS activity fell below half of early-term level weight 13  (odds ratio 28.8)
--   Under 60% of submissions on time               weight  9  (odds ratio 8.58)
--   No advisor contact this term                   weight  2  (odds ratio 1.82)
--   Advisor contact attempted, none kept           weight  6  (odds ratio 4.6)
--   Aid offered but not accepted                   weight  0  (odds ratio n/a)
--   Unresolved financial support case              weight 19  (odds ratio 126.33)
--   Other support case open                        weight  0  (odds ratio 0.19)
-- Score = sum of active flag weights, scaled to 0-100 by the total weight.
-- Levels (from observed non-return rates by score band):
--   High >= 50, Moderate >= 40.
--
-- The reason string is assembled with scalar expressions only (CONCAT_WS in
-- descending-weight order, truncated after the third item): APPLY operators
-- here sent the optimizer into a minutes-long plan, while this form runs at
-- the speed of the signals query itself.
--
-- PERFORMANCE: append OPTION (FORCE ORDER) to any query that filters this
-- view (e.g. WHERE TermCurrentTermFlag = 'Y'). Without it the optimizer
-- pushes the predicate into a nested-loops re-aggregation of the LMS fact
-- and the query runs for minutes; with it, milliseconds.
-- ---------------------------------------------------------------------------
CREATE OR ALTER VIEW data.StudentRisk
AS
WITH hist AS (
    SELECT StudentCode, StudentName, TermCode, ProgramCode, ProgramName,
           TermStartDate, TermEndDate, TermCurrentTermFlag, AcademicStandingName,
           TermGPAValue, CreditHoursAttempted, CreditHoursEarned,
           -- a term with no posted grades (TermGPAValue NULL, e.g. the term in
           -- progress) has no completion evidence yet: NULL, not zero
           CompletionRatio = CASE WHEN CreditHoursAttempted > 0 AND TermGPAValue IS NOT NULL
                                  THEN CreditHoursEarned / CreditHoursAttempted END
    FROM data.StudentHistory
    WHERE StudentStatusEnrolledFlag = 'Y'
), acad AS (
    SELECT *,
           PriorTermGPAValue    = LAG(TermGPAValue)    OVER (PARTITION BY StudentCode ORDER BY TermStartDate),
           PriorCompletionRatio = LAG(CompletionRatio) OVER (PARTITION BY StudentCode ORDER BY TermStartDate)
    FROM hist
), week_totals AS (      -- LMS: collapse classes to one row per student-term-week
    SELECT StudentCode, TermCode, WeekStartDate,
           Acts   = SUM(LoginCount + SubmissionCount),
           Subs   = SUM(SubmissionCount),
           OnTime = SUM(OnTimeSubmissionCount)
    FROM data.LearningActivity
    GROUP BY StudentCode, TermCode, WeekStartDate
), term_weeks AS (       -- week index within each term, from the LMS calendar itself
    SELECT TermCode, WeekStartDate,
           WeekNumber = DENSE_RANK() OVER (PARTITION BY TermCode ORDER BY WeekStartDate),
           WeekCount  = COUNT(*)    OVER (PARTITION BY TermCode)
    FROM (SELECT DISTINCT TermCode, WeekStartDate FROM data.LearningActivity) w
), term_asof AS (        -- "now" for a term = the last seeded LMS week
    SELECT TermCode, AsOfDate = DATEADD(day, 6, MAX(WeekStartDate))
    FROM term_weeks GROUP BY TermCode
), lms AS (
    SELECT w.StudentCode, w.TermCode,
           LastActivityDate = MAX(CASE WHEN w.Acts > 0 THEN DATEADD(day, 6, w.WeekStartDate) END),
           EarlyAvg = AVG(CASE WHEN t.WeekNumber <= t.WeekCount / 2.0 THEN 1.0 * w.Acts END),
           LateAvg  = AVG(CASE WHEN t.WeekNumber >  t.WeekCount / 2.0 THEN 1.0 * w.Acts END),
           Subs = SUM(w.Subs), OnTime = SUM(w.OnTime)
    FROM week_totals w
    JOIN term_weeks t ON t.TermCode = w.TermCode AND t.WeekStartDate = w.WeekStartDate
    GROUP BY w.StudentCode, w.TermCode
), adv AS (
    SELECT StudentCode, TermCode,
           Contacts = SUM(ContactCount), Kept = SUM(KeptCount), Missed = SUM(MissedCount),
           LastContactDate = MAX(ContactDate)
    FROM data.AdvisorContact
    GROUP BY StudentCode, TermCode
), aid AS (
    SELECT StudentCode, TermCode,
           Offered   = SUM(OfferedAmount),
           Accepted  = SUM(ISNULL(AcceptedAmount, 0)),
           Disbursed = SUM(ISNULL(DisbursedAmount, 0))
    FROM data.FinancialAid
    GROUP BY StudentCode, TermCode
), cases AS (
    SELECT StudentCode, TermCode,
           OpenFinancialCases = SUM(CASE WHEN CaseProfileOpenFlag = 'Y' AND CaseProfileCategoryCode = 'FIN'  THEN CaseCount ELSE 0 END),
           OpenFinancialDays  = MAX(CASE WHEN CaseProfileOpenFlag = 'Y' AND CaseProfileCategoryCode = 'FIN'  THEN DaysOpen END),
           OpenTechnicalCases = SUM(CASE WHEN CaseProfileOpenFlag = 'Y' AND CaseProfileCategoryCode = 'TECH' THEN CaseCount ELSE 0 END),
           OpenPersonalCases  = SUM(CASE WHEN CaseProfileOpenFlag = 'Y' AND CaseProfileCategoryCode = 'PERS' THEN CaseCount ELSE 0 END),
           OpenAcademicCases  = SUM(CASE WHEN CaseProfileOpenFlag = 'Y' AND CaseProfileCategoryCode = 'ACAD' THEN CaseCount ELSE 0 END)
    FROM data.SupportCase
    GROUP BY StudentCode, TermCode
), signals AS (
    SELECT a.StudentCode, a.StudentName, a.TermCode, a.TermStartDate, a.TermCurrentTermFlag,
           a.ProgramCode, a.ProgramName, a.AcademicStandingName,
           a.TermGPAValue, a.PriorTermGPAValue,
           EffectiveGPA             = COALESCE(a.TermGPAValue, a.PriorTermGPAValue),
           a.CreditHoursAttempted, a.CreditHoursEarned,
           a.CompletionRatio, a.PriorCompletionRatio,
           EffectiveCompletionRatio = COALESCE(a.CompletionRatio, a.PriorCompletionRatio),
           CompletionChange         = a.CompletionRatio - a.PriorCompletionRatio,
           DaysSinceLastActivity = DATEDIFF(day, l.LastActivityDate, ISNULL(ta.AsOfDate, a.TermEndDate)),
           ActivityTrendPct = CASE WHEN l.EarlyAvg > 0
                                   THEN ROUND(100.0 * ISNULL(l.LateAvg, 0) / l.EarlyAvg, 0) END,
           SubmissionCount = ISNULL(l.Subs, 0),
           OnTimeSharePct  = CASE WHEN l.Subs > 0 THEN ROUND(100.0 * l.OnTime / l.Subs, 0) END,
           AdvisorContacts = ISNULL(v.Contacts, 0),
           AdvisorKept     = ISNULL(v.Kept, 0),
           AdvisorMissed   = ISNULL(v.Missed, 0),
           DaysSinceLastContact = DATEDIFF(day, v.LastContactDate, ISNULL(ta.AsOfDate, a.TermEndDate)),
           AidOffered   = ISNULL(f.Offered, 0),
           AidAccepted  = ISNULL(f.Accepted, 0),
           AidDisbursed = ISNULL(f.Disbursed, 0),
           OpenFinancialCases = ISNULL(c.OpenFinancialCases, 0),
           OpenFinancialDays  = c.OpenFinancialDays,
           OpenTechnicalCases = ISNULL(c.OpenTechnicalCases, 0),
           OpenPersonalCases  = ISNULL(c.OpenPersonalCases, 0),
           OpenAcademicCases  = ISNULL(c.OpenAcademicCases, 0),
           FlagLowGPA            = CASE WHEN COALESCE(a.TermGPAValue, a.PriorTermGPAValue) < 2.0 THEN 1 ELSE 0 END,
           FlagLowCompletion     = CASE WHEN COALESCE(a.CompletionRatio, a.PriorCompletionRatio) < 0.5 THEN 1 ELSE 0 END,
           FlagCompletionDrop    = CASE WHEN a.PriorCompletionRatio - a.CompletionRatio > 0.3 THEN 1 ELSE 0 END,
           FlagInactiveLMS       = CASE WHEN l.LastActivityDate IS NULL
                                          OR DATEDIFF(day, l.LastActivityDate, ISNULL(ta.AsOfDate, a.TermEndDate)) >= 14 THEN 1 ELSE 0 END,
           FlagDecliningLMS      = CASE WHEN l.EarlyAvg > 0 AND ISNULL(l.LateAvg, 0) < 0.5 * l.EarlyAvg THEN 1 ELSE 0 END,
           FlagLateSubmissions   = CASE WHEN l.Subs > 0 AND 1.0 * l.OnTime / l.Subs < 0.6 THEN 1 ELSE 0 END,
           FlagNoAdvisorContact  = CASE WHEN ISNULL(v.Contacts, 0) = 0 THEN 1 ELSE 0 END,
           FlagAdvisorMissed     = CASE WHEN ISNULL(v.Missed, 0) > 0 AND ISNULL(v.Kept, 0) = 0 THEN 1 ELSE 0 END,
           FlagAidUnaccepted     = CASE WHEN ISNULL(f.Offered, 0) > 0 AND ISNULL(f.Accepted, 0) = 0 THEN 1 ELSE 0 END,
           FlagOpenFinancialCase = CASE WHEN ISNULL(c.OpenFinancialCases, 0) > 0 THEN 1 ELSE 0 END,
           FlagOpenOtherCase     = CASE WHEN ISNULL(c.OpenTechnicalCases, 0) + ISNULL(c.OpenPersonalCases, 0)
                                           + ISNULL(c.OpenAcademicCases, 0) > 0 THEN 1 ELSE 0 END
    FROM acad a
    LEFT JOIN term_asof ta ON ta.TermCode = a.TermCode
    LEFT JOIN lms   l ON l.StudentCode = a.StudentCode AND l.TermCode = a.TermCode
    LEFT JOIN adv   v ON v.StudentCode = a.StudentCode AND v.TermCode = a.TermCode
    LEFT JOIN aid   f ON f.StudentCode = a.StudentCode AND f.TermCode = a.TermCode
    LEFT JOIN cases c ON c.StudentCode = a.StudentCode AND c.TermCode = a.TermCode
)
, scored AS (
    SELECT s.*,
           RiskScore = CAST(ROUND(100.0 * (
               s.FlagLowGPA * 0 +
               s.FlagLowCompletion * 0 +
               s.FlagCompletionDrop * 1 +
               s.FlagInactiveLMS * 17 +
               s.FlagDecliningLMS * 13 +
               s.FlagLateSubmissions * 9 +
               s.FlagNoAdvisorContact * 2 +
               s.FlagAdvisorMissed * 6 +
               s.FlagAidUnaccepted * 0 +
               s.FlagOpenFinancialCase * 19 +
               s.FlagOpenOtherCase * 0
           ) / 67, 0) AS int),
           FullReasons = CONCAT_WS('; ',
               CASE WHEN s.FlagOpenFinancialCase = 1 THEN CONCAT('financial support case unresolved for ', s.OpenFinancialDays, ' days') END,
               CASE WHEN s.FlagInactiveLMS = 1 THEN CONCAT('no LMS activity for ', s.DaysSinceLastActivity, ' days') END,
               CASE WHEN s.FlagDecliningLMS = 1 THEN CONCAT('LMS activity down to ', CAST(s.ActivityTrendPct AS int), '% of early-term level') END,
               CASE WHEN s.FlagLateSubmissions = 1 THEN CONCAT('only ', CAST(s.OnTimeSharePct AS int), '% of submissions on time') END,
               CASE WHEN s.FlagAdvisorMissed = 1 THEN CONCAT(s.AdvisorMissed, ' advisor contact(s) missed, none kept') END,
               CASE WHEN s.FlagNoAdvisorContact = 1 THEN 'no advisor contact this term' END,
               CASE WHEN s.FlagCompletionDrop = 1 THEN CONCAT('completion ratio fell ', CAST(ROUND(-100 * s.CompletionChange, 0) AS int), ' points from prior term') END
           )
    FROM signals s
), position1 AS (
    SELECT scored.*, Position1 = CHARINDEX('; ', FullReasons) FROM scored
), position2 AS (
    SELECT position1.*,
           Position2 = CASE WHEN Position1 > 0 THEN CHARINDEX('; ', FullReasons, Position1 + 2) ELSE 0 END
    FROM position1
), position3 AS (
    SELECT position2.*,
           Position3 = CASE WHEN Position2 > 0 THEN CHARINDEX('; ', FullReasons, Position2 + 2) ELSE 0 END
    FROM position2
)
SELECT StudentCode, StudentName, TermCode, TermStartDate, TermCurrentTermFlag,
       ProgramCode, ProgramName, AcademicStandingName,
       TermGPAValue, PriorTermGPAValue, EffectiveGPA,
       CreditHoursAttempted, CreditHoursEarned,
       CompletionRatio, PriorCompletionRatio, EffectiveCompletionRatio, CompletionChange,
       DaysSinceLastActivity, ActivityTrendPct, SubmissionCount, OnTimeSharePct,
       AdvisorContacts, AdvisorKept, AdvisorMissed, DaysSinceLastContact,
       AidOffered, AidAccepted, AidDisbursed,
       OpenFinancialCases, OpenFinancialDays, OpenTechnicalCases, OpenPersonalCases, OpenAcademicCases,
       FlagLowGPA, FlagLowCompletion, FlagCompletionDrop,
       FlagInactiveLMS, FlagDecliningLMS, FlagLateSubmissions,
       FlagNoAdvisorContact, FlagAdvisorMissed, FlagAidUnaccepted,
       FlagOpenFinancialCase, FlagOpenOtherCase,
       RiskScore,
       RiskLevel = CASE WHEN RiskScore >= 50 THEN 'High'
                        WHEN RiskScore >= 40  THEN 'Moderate'
                        ELSE 'Low' END,
       RiskReasons = CASE WHEN FullReasons = '' THEN 'no active risk signals'
                          WHEN Position3 > 0 THEN LEFT(FullReasons, Position3 - 1)
                          ELSE FullReasons END
FROM position3;
